main/urls.py
from django.urls import path 
from . import views
from .views import AdminPage, BookingUpdateView, feedback
urlpatterns = [
    path('admin_dashboard/', views.AdminPage, name="admin_dashboard"),
    path('timetable/', views.timetable, name="timetable"),
    path('get_booking/', views.get_booking, name="get_booking"),
    path('get_booking/<int:booking_id>/', views.get_booking, name="get_booking"),
    path('profile/', views.profilePage, name="profile"),
    path('petprofile/', views.PetprofilePage, name="petprofile"),
    path('edit_pet/<int:pet_id>', views.edit_pet, name="edit_pet"),
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('bookingpage/', views.BookingPage, name="bookingpage"),
    path('update_times/', views.update_times, name='update_times'),    
    path('calendar/', views.CalendarPage, name="calendar"),    
    path('all_bookings/', views.all_bookings, name="all_bookings"),    
    path('rooms/<int:room_id>/', views.room_detail, name='room_detail'),
    path('create_room/', views.create_room, name='create_room'),
    path('resize_booking/', views.resize_booking, name="resize_booking"),    
    path('update_booking_dates/', views.update_booking_dates, name="update_booking_dates"),    
    path('get_room_events/<int:room_id>/', views.get_room_events, name='get_room_events'),    
    path('',views.home, name="home"),
    path('edit-booking/<int:booking_id>/', views.edit_booking, name='edit_booking'),
    path('ownerprofile/<int:booking_id>/', views.ownerpf, name='ownerpf'),
    path('customer_booking/', views.customer_booking, name='customer_booking'),
    path('feedback/', views.feedback, name='feedback'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import random
# import datetime

# Create your models here.

class Owner(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15, blank=True)
    email = models.EmailField(blank=True)

    def __str__(self):
        # return f"{self.id},{self.user},{self.email}"
        return self.user.username
    
    def save(self, *args, **kwargs):
        self.email = self.user.email
        super().save(*args, **kwargs)
    
class Pet(models.Model):
    name = models.CharField(max_length=20)
    owner = models.ForeignKey(Owner, null=True, on_delete=models.CASCADE)
    age = models.PositiveBigIntegerField()
    species = models.CharField(max_length=50)
    breed = models.CharField(max_length=50)
    profile_pic = models.ImageField(default="profile.jpg", null=True, blank=True)

    def __str__(self):
        return self.name    
    
class Room(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name    

    
class Booking(models.Model):
    owner = models.ForeignKey(Owner, null=True, on_delete=models.CASCADE)
    pet = models.ManyToManyField(Pet)
    room = models.ForeignKey(Room, null=True, on_delete=models.CASCADE)
    date = models.DateField(blank=True, null=True)
    TIME_CHOICES = [
        ('09:00', '9:00'),
        ('10:00', '10:00'),
        ('11:00', '11:00'),
        ('12:00', '12:00'),
        ('14:00', '2:00'),
        ('15:00', '3:00'),
        ('16:00', '4:00'),
        ('17:00', '5:00'),
        ('full_day', 'Full (7:00-19:00)'),
        ('morning', 'Morning (7:00-12:00)'),
        ('noon', 'Noon (13:00-19:00)'),
    ]
    time = models.CharField(max_length=10, choices=TIME_CHOICES, blank=True, null=True)
    SERVICE_CHOICES = [
        ('Hair Grooming', 'Hair Grooming'),
        ('Bath and Dry', 'Bath and Dry'),
        ('Pet Hotel', 'Pet Hotel'),
        ('Pet Daycare', 'Pet Daycare'),
    ]
    service = models.CharField(max_length=50, choices=SERVICE_CHOICES)
    STATUS_CHOICES = [
        ('Ongoing', 'Ongoing'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Ongoing')

    def __str__(self):
        return f'{self.owner.user.username} - {self.date} {self.time}'      
    
    checkin = models.DateField(null=True, blank=True)
    checkout = models.DateField(null=True, blank=True)

class Feedback(models.Model):
    owner = models.ForeignKey(Owner, null=True, on_delete=models.CASCADE)
    rating = models.IntegerField()
    comment = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'Rating: {self.rating}, Comment: {self.comment}'

main/templates/admin_dashboard.html
{% extends 'base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <style>

        .container {
            max-width: 1200px;
            margin: 20px auto;
            padding: 0 20px;
        }
        .header {
            background-color: #333;
            color: #fff;
            padding: 20px;
            text-align: center;
        }
        .menu {
            background-color: #f4f4f4;
            padding: 10px;
            border-radius: 5px;
        }
        .menu ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }
        .menu ul li {
            display: inline;
            margin-right: 10px;
        }
        .content {
            margin-top: 20px;
        }
        .card {
            background-color: #fff;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .sorting-form {
           display: flex;
           align-items: center;
        }

        .sorting-form label {
            margin-right: 10px;
            margin-left: 50px;
        }

        .sort-select {
            padding: 8px;
            border-radius: 5px;
        }

        .sort-button {
            background-color: rgb(102, 58, 60);
            border: none;
            color: white;
            padding: 8px 16px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 14px;
            border-radius: 5px;
            cursor: pointer;
        }

        .sort-button:hover {
            background-color: rgb(255,223,203);
            color: rgb(102, 58, 60);
        }
        .a {
            margin: 10px auto;
            width: 96%;
            border-collapse: collapse;
        }
        .a th, td {
            border: 1px solid rgb(102, 58, 60);
            padding: 8px;
            text-align: left;
            background-color: white;
        }
        .a th {
            background-color: rgb(255,223,203);
        }
        .dash {
            color: black ;
            font-size: 25px;
        }   
        .dashb {
            text-align: center; 
            margin-top: 20px;
        }
        .button-tt {
            background-color: rgb(102, 58, 60);
            border: none;
            color: white;
            padding: 8px 16px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 20px; 
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 5px;
        }
        .button-tt:hover {
            background-color: rgb(255,223,203);
            color: rgb(102, 58, 60);
        }
    
        .button {
            background-color: rgb(102, 58, 60);
            border: none;
            color: white;
            padding: 8px 16px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 14px; 
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 5px;
        }
        .button:hover {
            background-color: rgb(255,223,203);
            color: rgb(102, 58, 60);
        }

        .button-complete {
            background-color: green;
            border: none;
            color: white;
            padding: 8px 16px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 14px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 5px;
        }
        .button-complete:hover {
            background-color: lightgreen;
        }

        .button-ongoing {
            background-color: darkorange;
            border: none;
            color: white;
            padding: 8px 16px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 14px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 5px;
        }
        .button-ongoing:hover {
            background-color:orange;
        }

        .button-cancel {
            background-color: red;
            border: none;
            color: white;
            padding: 8px 16px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 14px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 5px;
        }
        .button-cancel:hover {
            background-color: darkred;
        }
        .room-list {
            list-style-type: none;
            margin: 0;
            padding: 0;
            text-align: right;
            margin-top: 20px; 
            margin-bottom: 20px;
            margin-right: 30px;
        }

        .room-list li ,
        .cr{
            display: inline-block;
            margin-right: 10px;
            background-color: #f0f0f0;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .room-list li a ,
        .cr{
            text-decoration: none;
            color: #333;
            font-weight: bold;
        }

        .room-list li a:hover ,
        .cr{
            color: #0066cc;
        }
        .cr{
            width: 40px;
        }
        .timetable {
        display: inline-block;
        background-color: rgb(102, 58, 60);
        border: none;
        color: white;
        padding: 10px 20px;
        margin-left: 50px;
        text-align: left;
        text-decoration: none;
        font-size: 16px;
        border-radius: 5px;
        cursor: pointer;
        
    }
        .timetable:hover {
            background-color: rgb(255,223,203);
            color: rgb(102, 58, 60);
            text-decoration: none;

        }


    </style>
</head>
    <h1 class="dashb">Admin Dashboard</h1>
    <div style="margin-top: 20px; margin-bottom: 20px;">
    <h2 class="dash">Customer bookings</h2>
    <a  class="timetable" href="{% url 'timetable' %}">timetable</a>

    <ul class="room-list">
        {% for room in rooms %}
            <li>
                <a href="{% url 'room_detail' room.id %}">Room {{ room.name }}</a>
            </li>
        {% endfor %}
        <a href="{% url 'create_room' %}">
            <button class="cr" type="button">+</button>
        </a>
    
    </ul>
    

    <form method="GET" action="" class="sorting-form">
    <label for="sort_by">Sort By:</label>
    <select name="sort_by" id="sort_by" class="sort-select">
        <option value="date">Date</option>
        <option value="id">Booking ID</option>
        <option value="service">Type of services</option>
    </select>
    <button type="submit" class="sort-button">Sort</button>
</form>
<table class="a">
    <thead>
        <tr>
            <th>Booking ID</th>
            <th>Customer name</th>
            <th>Pet name</th>
            <th>Date</th>
            <th>Time</th>
            <th>Checkin</th>
            <th>Checkout</th>
            <th>Service</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for booking in ongoing_bookings %}
        <tr>
            <td>{{ booking.id }}</td>
            <td><a href="{% url 'ownerpf' booking.id %}">{{ booking.owner.user.username }}</a></td>
            <td>
                {% for pet in booking.pet.all %}
                    {{ pet.name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>            
            <td>{{ booking.date|default:"-" }}</td>
            <td>{{ booking.time|default:"-" }}</td>
            <td>{{ booking.checkin|default:"-" }}</td>
            <td>{{ booking.checkout|default:"-" }}</td>
            <td>{{ booking.service }}</td>
            <td>{{ booking.status }}</td>
            <td>
                {% if booking.service != 'Pet Hotel' %}
                <form method="post" action="{% url 'edit_booking' booking.id %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="button">Edit Booking</button>
                </form>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="booking_id" value="{{ booking.id }}">
                    <input type="hidden" name="status" value="Completed">
                    <button type="submit" class="button-complete">Complete booking</button>
                </form>
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="booking_id" value="{{ booking.id }}">
                    <input type="hidden" name="status" value="Cancelled">
                    <button type="submit" class="button-cancel" >Cancel booking</button>
                </form>            
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

<div style="margin-top: 70px; margin-bottom: 70px;">
<h2 class="dash">Completed Bookings</h2>
<table class="a">
    <thead>
        <tr>
            <th>Booking ID</th>
            <th>Customer name</th>
            <th>Pet name</th>
            <th>Date</th>
            <th>Time</th>
            <th>Checkin</th>
            <th>Checkout</th>
            <th>Service</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for booking in completed_bookings %}
        <tr>
            <td>{{ booking.id }}</td>
            <td><a href="{% url 'ownerpf' booking.id %}">{{ booking.owner.user.username }}</a></td>
            <td>
                {% for pet in booking.pet.all %}
                    {{ pet.name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>            
            <td>{{ booking.date|default:"-" }}</td>
            <td>{{ booking.time|default:"-" }}</td>
            <td>{{ booking.checkin|default:"-" }}</td>
            <td>{{ booking.checkout|default:"-" }}</td>
            <td>{{ booking.service }}</td>
            <td>{{ booking.status }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div style="margin-top: 70px; margin-bottom: 70px;">
    <h2 class="dash">Cancelled Bookings</h2>
    <table class="a">
    <thead>
        <tr>
            <th>Booking ID</th>
            <th>Customer name</th>
            <th>Pet name</th>
            <th>Date</th>
            <th>Time</th>
            <th>Checkin</th>
            <th>Checkout</th>
            <th>Service</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for booking in cancelled_bookings %}
        <tr>
            <td>{{ booking.id }}</td>
            <td><a href="{% url 'ownerpf' booking.id %}">{{ booking.owner.user.username }}</a></td>
            <td>
                {% for pet in booking.pet.all %}
                    {{ pet.name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>
            </td>            
            <td>{{ booking.date|default:"-" }}</td>
            <td>{{ booking.time|default:"-" }}</td>
            <td>{{ booking.checkin|default:"-" }}</td>
            <td>{{ booking.checkout|default:"-" }}</td>
            <td>{{ booking.service }}</td>
            <td>{{ booking.status }}</td>
        </tr>
        {% endfor %}
        
    </tbody>
    </table>
</div>
</html>
{% endblock %}

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PetPals</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        
        body {
            font-family: "Quicksand", sans-serif;
            font-optical-sizing: auto;
            font-weight: 600;
            font-style: normal;
            margin: 0 !important;
            padding: 0;
            background-color: #F9F2EB;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        h2 {
            text-align: center;
            color: #8B4513; 
            margin-bottom: 20px;
            font-size: xx-large;
        }

        footer {
            background-color: rgb(102, 58, 60);
            color: white;
            padding: 20px 0;
            text-align: center;
            margin-top: 100px; 
            width: 100%;        
        }

        .footer-content {
            max-width: 960px;
            margin: 0 auto;
        }

        .footer-content p {
            margin: 5px 0;
        }

        .contact {
            color: #fff;
        }

        .ope {
            width: 80%;
            border-collapse: collapse;
            margin: 0 auto;
            background-color: rgba(255, 255, 255, 0.7); 
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .ope th, .ope td {
            padding: 12px;
            text-align: left;
            border: none;
            font-size: 16px;
            color: #000; 
        }

        .ope th {
            background-color: #8B4513; 
            text-transform: uppercase;
            color: #FFF; 
        }

        .ope td {
            background-color: #D2B48C; 
        }

        .ope r:last-child td {
            border-bottom: none;
        }

        .ti {
            margin-top: 20px;
        }

        .floating-icon {
            position: fixed;
            bottom: 20px;
            right: 20px;
            color: #fff;
            padding: 15px;
            border-radius: 50%;
            cursor: pointer;
        }


        .fas {
            font-size: 24px;
        }
    </style>
</head>
<body>
    {% include 'navbar.html' %}
    <p style="color: white; background-color: red; font-size: larger; text-align: center;">This is a sample website for a project only and does not present for a real business.</p>

    {% block content %}

    {% endblock %}
    {% if request.user.is_authenticated %}
    <div>
        <a href="{% url 'feedback' %}" class="floating-icon">
            <img src="{% static 'image/catdog.png' %}" alt="PawBanner" style="width: 50px; height: 50px;">   </a>    
    </div>
    {% endif %}
    <footer>
        <div class="footer-content">
            <h2 class="contact">Contact Us</h2>
            <p>31, Jalan SS20/11, Damansara Utama, Petaling Jaya, 47400, Petaling Jaya, Selangor</p>
            <p>Phone/WhatsApp: 03-7722 4584</p>
            <p>Email: petpalsofficial@gmail.com</p>
        </div>
    </footer>
</body>
</html>

main/templates/edit_pet.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
    .container {
    max-width: 700px;
    margin-top: 50px ;
    margin-right: 10px;
    margin-left: 10px;
    background-color: #fff;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    .card {
    max-width: 350px;
    border-radius: 8px;
    margin-left: 200px;
    margin-right: 30px;
    margin-top: 50px;
    padding: 20px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);

    }

    h1 {
        text-align: center;
    }

    form {
        margin-top: 20px;
    }

    form .form-group {
        margin-bottom: 15px;
    }

    form label {
        display: block;
        font-weight: bold;
    }

    form input[type="text"],
    form input[type="email"],
    #id_age {
      width: 100%;
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
    }
    form button[type="submit"] {
      background-color: #007bff;
      color: #fff;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-size: 16px;
    }
    
    .button-container {
        padding-left: 2%;
    }
    .profile_pic {
        width: 170px;
        height: 150px;
        border-radius: 50%;
        margin: 0 auto;
        overflow: hidden;
        border: 2px solid #100f0f;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .profile_pic img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }
    

</style>
<body>
    <h1 class="ti">Edit Pet Profile</h1>
    <div class="row">    
        <div class="col-md-5">
            <div class="card card-body">
                <a class="btn btn-warning" href="{% url 'petprofile' %}"> &#8592; Back to Profile</a>
                <hr>
                <h3 style="text-align: center">{{ pet_instance.name }}</h3>
                <hr>
                {% if pet_instance.profile_pic %}
                    <img class="profile_pic" src="{{ pet_instance.profile_pic.url }}" >
                {% else %}
                    <img class="profile_pic" src="{% static 'image/profile.jpg' %}" >
                {% endif %}

            
            </div>
        </div>
        <div class="col-md-5">
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="container">
                    <div class=" form-group">
                        <label for="id_name">Name:</label>
                        <input type="text" id="id_name" name="name" value="{{ pet_instance.name }}">
                    </div>
                    <div class=" form-group">
                        <label for="id_age">Age:</label>
                        <input type="text" id="id_age" name="age" value="{{ pet_instance.age }}">
                    </div>
                    <div class=" form-group">
                        <label for="id_species">Species:</label>
                        <input type="text" id="id_species" name="species" value="{{ pet_instance.species }}">
                    </div>
                    <div class=" form-group">
                        <label for="id_breed">Breed:</label>
                        <input type="text" id="id_breed" name="breed" value="{{ pet_instance.breed }}">
                    </div>
                    <div class="form-group">
                        <label for="id_profilepic">Profile pic:</label>
                        {% if pet_instance.profile_pic %}
                            <p>Currently: <a href="{{ pet_instance.profile_pic.url }}">{{ pet_instance.profile_pic.name }}</a></p>
                            <p><input type="checkbox" name="profile_pic-clear" id="profile_pic-clear-id"> Clear</p>
                        {% endif %}
                        <p>Change: <input type="file" id="id_profilepic" name="profile_pic"></p>
                    </div>
                    

                    <div class="button-container">
                        <button type="submit">Save Changes</button>
                    </div>
                </div>
            </form>
        </div>
    </div>    
</body>
</html>
{% endblock %}

main/templates/petprofile.html
{% extends 'base.html' %}
{% block content %}
{% load static%}

<style>
    .container {
    max-width: 800px;
    margin: 20px auto;
    background-color: #fff;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h1 {
        text-align: center;
    }

    form {
        margin-top: 20px;
    }

    form .form-group {
        margin-bottom: 15px;
    }

    form label {
        display: block;
        font-weight: bold;
    }

    form input[type="text"],
    form input[type="email"],
    #id_age {
      width: 100%;
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
    }
    form input[type="submit"] {
      background-color: #007bff;
      color: #fff;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-size: 16px;
    }
    
    .button-container {
        padding-left: 25%;
    }

    #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
            text-align: center;
			border-radius: 5px;
        }
        
    .profile_pic {
        width: 120px;
        height: 120px;
        border-radius: 50%;
        margin: 0 auto;
        overflow: hidden;
        border: 2px solid #100f0f;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .profile_pic img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    .pet-card {
        text-align: center;
        padding: 10px;
        margin-bottom: 20px;
        margin-top: 20px;
        margin-left: 10px;
        margin-right: 10px;
        
    }

    .pet-card p {
        margin-top: 10px;
        font-size: 16px;
        font-weight: bold;
    }
    .pet-container {
        display: flex;
        justify-content: center;
        flex-wrap: wrap;
        gap: 20px;
    }


</style>

        <h1 class="ti">PetProfile</h1>
    </div>

    <div class="pet-container">
        {% for pet_instance in pet_instances %}
        <div class="pet-card">
            <div class=>
                <a href="{% url 'edit_pet' pet_instance.id %}">
                    <div class="profile_pic">
                        <img src="{% if pet_instance.profile_pic %}{{ pet_instance.profile_pic.url }}{% else %}{% static 'image/profile.jpg' %}{% endif %}" alt="{{ pet_instance.name }}'s Profile Picture">
                    </div>
                </a>
                <div>
                    <p>{{ pet_instance.name }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <div class=" form-group">
                <label for="id_username">Name:</label>
                {{ form.name }}
            </div>
            <div class=" form-group">
                <label for="id_breed">Age:</label>
                {{ form.age }}
            </div>
            <div class=" form-group">
                <label for="id_age">Species:</label>
                {{ form.species }}
            </div>
            <div class=" form-group">
                <label for="id_species">Breed:</label>
                {{ form.breed }}
            </div>
            <div class=" form-group">
                <label for="id_profilepic">ProfilePic:</label>
                {{ form.profile_pic }}
            </div>


            {% for message in messages %}
                <p id="messages">{{ message }}</p>
            {% endfor %}
        </div>
        <div class="button-container">
            <input type="submit" value="Create Profile">
        </div>
        
    </form>
{% endblock %}

main/templates/profile.html
{% extends 'base.html' %}
{% block content %}

<style>
    .container {
    max-width: 800px;
    margin: 20px auto;
    background-color: #fff;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .bigcontainer{
        max-width: 900px;
        margin: 20px auto;
        padding: 20px;
        background-color: aqua;
        border-radius: 8px;
    }
    h1 {
        text-align: center;
    }

    form {
        margin-top: 20px;
    }

    form .form-group {
        margin-bottom: 15px;
    }

    form label {
        display: block;
        font-weight: bold;
    }

    form input[type="text"],
    form input[type="email"] {
      width: 100%;
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
    }
    form input[type="submit"] {
      background-color: #007bff;
      color: #fff;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-size: 16px;
    }

    .button-container {
        padding-left: 23%;
    }

    #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
            text-align: center;
			border-radius: 5px;
        }

</style>

    <div class="">
        <h1 class="ti">Profile</h1>
        <form method="POST" action="">
            {% csrf_token %}
            <div class="container">
                <div class=" form-group">
                    <label for="id_username">Name:</label>
                    {{ u_form.username }}
                </div>
                <div class=" form-group">
                    <label for="id_email">Email:</label>
                    {{ u_form.email }}
                </div>
                <div class=" form-group">
                    <label for="id_phonenum">PhoneNumber:</label>
                    {{ o_form.phone_number }}
                </div>
                {% for message in messages %}
                    <p id="messages">{{ message }}</p>
                {% endfor %}
            </div>
            <div class="button-container">
                <input type="submit" value="Save Profile">
            </div>
        </form>
    </div>
{% endblock %}